In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.impute import SimpleImputer
from sklearn.compose import ColumnTransformer

In [2]:
df=pd.read_csv('titanic_toy.csv')

In [3]:
df.head()

Age     Fare  Family  Survived
0  22.0   7.2500       1         0
1  38.0  71.2833       1         1
2  26.0   7.9250       0         1
3  35.0  53.1000       1         1
4  35.0   8.0500       0         0

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Age       714 non-null    float64
 1   Fare      846 non-null    float64
 2   Family    891 non-null    int64  
 3   Survived  891 non-null    int64  
dtypes: float64(2), int64(2)
memory usage: 28.0 KB


In [5]:
df.isnull().mean()

Age         0.198653
Fare        0.050505
Family      0.000000
Survived    0.000000
dtype: float64

In [6]:
x_train,x_test,y_train,y_test=train_test_split(df.drop('Survived',axis=1),df.Survived)

In [8]:
x_train.isnull().mean()

Age       0.199102
Fare      0.049401
Family    0.000000
dtype: float64

In [9]:
i1=SimpleImputer(strategy='median')
i2=SimpleImputer(strategy='mean')

In [10]:
trf=ColumnTransformer(transformers=[
    ('one',i1,['Age']),
    ('two',i2,['Fare'])
],remainder='passthrough')

In [11]:
trf.fit(x_train)

ColumnTransformer(remainder='passthrough',
                  transformers=[('one', SimpleImputer(strategy='median'),
                                 ['Age']),
                                ('two', SimpleImputer(), ['Fare'])])

In [13]:
trf.named_transformers_['one'].statistics_

array([28.])

In [14]:
trf.named_transformers_['two'].statistics_

array([30.67122661])

In [15]:
trf.fit_transform(x_train)

array([[ 28.    ,  12.35  ,   0.    ],
       [ 39.    ,  13.    ,   0.    ],
       [ 18.    ,  18.    ,   2.    ],
       ...,
       [ 35.    , 512.3292,   0.    ],
       [ 41.    ,  39.6875,   5.    ],
       [ 28.    ,   7.7958,   0.    ]])

In [17]:
trf.transform(x_test)

array([[ 29.        ,  37.11891611,   4.        ],
       [ 39.        ,  55.9       ,   1.        ],
       [ 44.        ,  90.        ,   2.        ],
       [ 58.        ,  29.7       ,   0.        ],
       [ 30.        ,  27.75      ,   0.        ],
       [ 54.        ,  14.        ,   0.        ],
       [ 29.        ,   7.55      ,   0.        ],
       [ 29.        ,   7.25      ,   0.        ],
       [ 17.        , 108.9       ,   1.        ],
       [ 29.        ,  22.3583    ,   2.        ],
       [ 29.        , 146.5208    ,   1.        ],
       [  2.        ,  39.6875    ,   5.        ],
       [ 25.        ,  55.4417    ,   1.        ],
       [  1.        ,  39.6875    ,   5.        ],
       [ 24.        ,   7.05      ,   0.        ],
       [  6.        ,  33.        ,   1.        ],
       [ 36.        ,  10.5       ,   0.        ],
       [ 29.        ,   6.95      ,   0.        ],
       [ 48.        ,  76.7292    ,   1.        ],
       [ 47.        ,  14.5    